name: build and deploy python 3.8 with dependencies

on:
  workflow_run:
    workflows: ["build-and-deploy-docker-python38-image"]
    types:
      - completed
  push:
    paths:
      - 'python3.8-with-dependencies/Dockerfile'
      - 'python3.8-with-dependencies/pyproject.toml'

jobs:
  build-python38-with-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
        run: |
          docker buildx build --tag mw-arm-test:latest --platform linux/amd64,linux/arm64 python3.8-with-dependencies/.
