# This is a basic workflow that is manually triggered

name: Manual python 3-8 build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-python38:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push --tag micwittmann/data-analysis-environment:python3.8 --platform linux/amd64,linux/arm64 python3.8/.
